.PHONY: all clean install

all:
	$(MAKE) -C core -f $(MINGW_MAKEFILE)

clean:
	$(MAKE) -C core -f $(MINGW_MAKEFILE) clean

rmbak:
	rm -f *~
	$(MAKE) -C core -f $(MINGW_MAKEFILE) rmbak

install: all
	$(MAKE) -C core -f $(MINGW_MAKEFILE) install
